### PR TITLE
PAY-3733: Upgrade libraries com.datadoghq, io.flow

### PR DESCRIPTION
**Pull request by pmlemos**
- com.datadoghq
  - dd-java-agent (1.37.0 => 1.37.1)
- io.flow
  - lib-log (0.2.22 => 0.2.23)
  - lib-metrics-play28 (1.0.93 => 1.0.94)
  - lib-postgresql-play-play28 (0.5.61 => 0.5.62)
  - lib-test-utils-play28 (0.2.36 => 0.2.37)
  - lib-usage-play28 (0.2.52 => 0.2.53)

### CODE REVIEW

**Comment by flow-tech** [comment]
helm diff detected no changes for registry

**Comment by flow-tech** [comment]
helm diff detected no changes for registry

**Comment by flow-tech** [comment]
Click here for code coverage report: https://jenkins.flo.pub/job/flowcommerce/job/registry/job/PR-574/2/scoverage-report/

**Comment by flow-tech** [comment]
helm diff detected no changes for registry

**Comment by flow-tech** [comment]
Click here for code coverage report: https://jenkins.flo.pub/job/flowcommerce/job/registry/job/PR-574/3/scoverage-report/

**Review by jlogeart — APPROVED** [review]

**Pull request merged**
